[package]
name = "nav"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "project_navigator"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = [ "derive" ]}
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"